apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: ravikumarmanchi/xyztechnologies:latest
        ports:
        - containerPort: 8080   # Tomcat inside container
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer
  selector:
    app: simple-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP